exec-once = systemctl --user start hyprpolkitagent
exec-once = swaync
exec-once = waybar
exec-once = waybar -c ~/.config/waybar/config-monitor2.jsonc -s ~/.config/waybar/style-monitor2.css
exec-once = hypridle
exec-once = xdg-desktop-portal-hyprland
exec-once = hyprpm reload -n
exec-once = wl-paste --type image --watch cliphist store # cliphist listener
exec-once = wl-paste --type text --watch cliphist store # cliphist listener
exec-once = wl-clip-persist --clipboard regular --all-mime-type-regex '^(?!x-kde-passwordManagerHint).+' # persists clipboard when applications close
exec-once = hyprsunset
exec-once = waypaper --restore
exec-once = copyparty -c ~/copyparty/example.conf
exec-once = hyprctl plugin load ~/hyprselect/hyprselect.so
exec-once = easyeffects --gapplication-service
