


#kvm

windowrule {
  name = windowrule-1
  idle_inhibit = always
  match:class = looking-glass-client
}



# rofi effects
windowrule {
  name = windowrule-2
  dim_around = on
  no_blur = on
  match:class = (Rofi)
}

windowrule {
  name = windowrule-3
  animation = popin
  match:class = .*
}

windowrule {
  name = windowrule-4
  immediate = on
  match:class = ^(overwatch.exe)$
}



#runelite tooltip fix

windowrule {
  name = windowrule-5
  no_initial_focus = on
  match:class = ^(net-runelite-client-RuneLite)$
  match:title = ^win(.*)$
}



#stremio

windowrule {
  name = windowrule-6
  opacity = 1.0 1.0
  match:class = ^(com.stremio.stremio)$
}



#waybar

layerrule {
  name = layerrule-1
  blur = on
  ignore_alpha = 0.5
  match:namespace = tofi-run
}


layerrule {
  name = layerrule-2
  blur = on
  ignore_alpha = 0.5
  match:namespace = waybar
}


#remove transparency from fullscreen things
windowrule {
  name = windowrule-7
  opacity = 1.0 override 1.0 override
  match:fullscreen = 1
}


#waydroid windows jank
windowrule {
  name = windowrule-8
  float = on
  size = 576 752
  match:title = Aegis
}

windowrule {
  name = windowrule-9
  float = on
  match:class = Waydroid
}

windowrule {
  name = windowrule-10
  float = on
  size = (monitor_w*0) (monitor_h*0)
  match:title = InputMethod
}



# wofi

layerrule {
  name = layerrule-3
  ignore_alpha = 0.5
  blur = on
  match:namespace = wofi
}



#swaync
layerrule {
  name = layerrule-4
  ignore_alpha = 0.5
  blur = on
  match:namespace = swaync-control-center
}

layerrule {
  name = layerrule-5
  ignore_alpha = 0.5
  blur = on
  match:namespace = swaync-notification-window
}


#wlogout

layerrule {
  name = layerrule-6
  blur = on
  ignore_alpha = 0.5
  match:namespace = logout_dialog
}



windowrule {
  name = windowrule-11
  opacity = 0.0 override
  no_anim = on
  no_initial_focus = on
  max_size = 1 1
  no_blur = on
  no_focus = on
  match:class = ^(xwaylandvideobridge)$
}
