


#kvm

windowrule = idleinhibit always, class:looking-glass-client


# rofi effects
windowrule = dimaround, class:(Rofi)
windowrule = noblur, class:(Rofi)
windowrule = animation popin, class:.*
windowrule = immediate, class:^(overwatch.exe)$


#runelite tooltip fix

windowrule = noinitialfocus,class:^(net-runelite-client-RuneLite)$,title:^win(.*)$


#stremio

windowrulev2 = opacity 1.0 1.0, class:^(com.stremio.stremio)$


#waybar

layerrule = blur, tofi-run
layerrule = ignorezero, tofi-run
layerrule = ignorealpha 0.5, tofi-run

layerrule = blur, waybar
layerrule = ignorezero, waybar
layerrule = ignorealpha 0.5, waybar

#remove transparency from fullscreen things
windowrulev2 = opacity 1.0 override 1.0 override, fullscreen:1

#waydroid windows jank
windowrulev2 = float, title:Aegis
windowrulev2 = float, class:Waydroid
windowrulev2 = size 576 752, title:Aegis
windowrulev2 = float, title:InputMethod
windowrulev2 = size 0% 0%, title:InputMethod


# wofi

layerrule = ignorezero, wofi
layerrule = ignorealpha 0.5, wofi
layerrule = blur, wofi


#swaync
layerrule = ignorezero, swaync-control-center
layerrule = ignorezero, swaync-notification-window
layerrule = ignorealpha 0.5, swaync-control-center
layerrule = ignorealpha 0.5, swaync-notification-window
layerrule = blur, swaync-control-center
layerrule = blur, swaync-notification-window

#wlogout

layerrule = blur, logout_dialog
layerrule = ignorezero, logout_dialog
layerrule = ignorealpha 0.5, logout_dialog


windowrule = opacity 0.0 override, class:^(xwaylandvideobridge)$
windowrule = noanim, class:^(xwaylandvideobridge)$
windowrule = noinitialfocus, class:^(xwaylandvideobridge)$
windowrule = maxsize 1 1, class:^(xwaylandvideobridge)$
windowrule = noblur, class:^(xwaylandvideobridge)$
windowrule = nofocus, class:^(xwaylandvideobridge)$