[colors]
background = '#1717118e'
black = '#171711'
blue = '#7897c1'
cursor = '#B9B9B8'
cyan = '#9cbd8a'
foreground = '#B9B9B8'
green = '#c1a978'
magenta = '#bd8a99'
red = '#9578c1'
tabs = '#B9B9B8'
tabs-active = '#78bcc1'
white = '#B9B9B8'
yellow = '#95aec7'
dim-black = '#1717118e'
dim-blue = '#7897c18e'
dim-cyan = '#9cbd8a8e'
dim-foreground = '#B9B9B88e'
dim-green = '#c1a9788e'
dim-magenta = '#bd8a998e'
dim-red = '#9578c18e'
dim-white = '#78bcc18e'
dim-yellow = '#95aec78e'
light-black = '#7897c1'
light-blue = '#9cbd8a'
light-cyan = '#c1a978'
light-foreground = '#bd8a99'
light-green = '#9578c1'
light-magenta = '#78bcc1'
light-red = '#95aec7'
light-white = '#7897c1'
light-yellow = '#9cbd8a'
