# Shell variables
# Generated by 'wal'
wallpaper="wildrose.jpg"

# Special
background='#171711'
foreground='#B9B9B8'
cursor='#B9B9B8'

# Colors
color0='#171711'
color1='#7897c1'
color2='#9cbd8a'
color3='#c1a978'
color4='#bd8a99'
color5='#9578c1'
color6='#78bcc1'
color7='#95aec7'
color8='#171711'
color9='#7897c1'
color10='#9cbd8a'
color11='#c1a978'
color12='#bd8a99'
color13='#9578c1'
color14='#78bcc1'
color15='#95aec7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
