--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="wildrose.jpg"

-- Special
background="#171711"
foreground="#B9B9B8"
cursor="#B9B9B8"

-- Colors
color0="#171711"
color1="#7897c1"
color2="#9cbd8a"
color3="#c1a978"
color4="#bd8a99"
color5="#9578c1"
color6="#78bcc1"
color7="#95aec7"
color8="#171711"
color9="#7897c1"
color10="#9cbd8a"
color11="#c1a978"
color12="#bd8a99"
color13="#9578c1"
color14="#78bcc1"
color15="#95aec7"
